### Refresh
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "grantType": "refresh_token",
  "refreshToken": "{{refreshToken}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}
