### Password Change
PUT http://localhost:8080/auth/change-password
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": {{adminId}},
  "oldPassword": "{{password}}",
  "newPassword": "{{password}}"
}