spring:
  application.name: durian
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # batch update: rewriteBatchedStatements=true (MySQL), useBatchMultiSend=true (MariaDB)
    url: "jdbc:mariadb://localhost/database?rewriteBatchedStatements=true&profileSQL=true"
    username: username
    password: password
    hikari:
      connectionInitSql: "SET NAMES utf8mb4"
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    open-in-view: false # lazy loading queries may be performed during view rendering if true
    hibernate.ddl-auto: validate # validate, create, create-drop., update, none
    # `hibernate.ddl-auto` is prior to `generate-ddl`. Thus, `generate-ddl` is ignored.
    # generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        # show_sql: true # show sql in stdout
        highlight_sql: true
        use_sql_comments: true # show JPQL (not SQL)
        default_batch_fetch_size: 500
  servlet:
    multipart:
      max-file-size: 4MB # default: 1MB
      max-request-size: 8MB # default: 10MB
      file-size-threshold: 0B # default: 0 (the size threshold after which files will be written to disk)
      # location: /var/www/uploads # default: a temporary directory
  cloud:
    aws:
      s3:
        region: ap-northeast-2
        bucket: your-bucket
      credentials:
        access-key: your-access-key
        secret-key: your-secret-key
  web.resources.add-mappings: false # resolves NoHandlerFoundException
  mvc.throw-exception-if-no-handler-found: true # resolves NoHandlerFoundException

security-config:
  content-security-policy: default-src 'none'
  cors:
    origins: "*"
    headers: "*"
    methods: "*"
    allow-credentials: true

logging:
  #  file:
  #    name: logs/spring.log
  level:
    kr.pincoin.durian: DEBUG
    org.hibernate.SQL: DEBUG # show sql in logger
    org.hibernate.orm.jdbc.bind: TRACE # show binding parameters (Spring boot 3+ and Hibernate 6+)

server.error:
  include-exception: false
  include-message: never
  include-stacktrace: never
  include-binding-errors: never
  whitelabel.enabled: false

pincoin:
  request-mapping:
    bank-callback: bank-callback
    paypal-callback: paypal-callback
    billgate-callback: billgate-callback
  scheduler:
    auth:
      user-manage: 0 10 4 * * * # every day 4:10 am
    shop:
      voucher-send: 3600000 # 3 second interval
      pending-order-delete: 0 */10 * * * * # every 10 minutes
      stock-alert: 0 0 8-23,0 * * * # every hour between 8 am and 1 am
      purchase-order: 0 1 10,14,18,23 * * * # every day 10, 14, 18, 23 hours

auth:
  jwt-secret-key: 0da12e06858fcb6b659d497437455ab16b3628b5391e392081660265e8e23044c66f9f7fade5932f77b6cd3438f1b4eb

aligo:
  api-key: api-key
  user-id: user-id
  sender: 01012341234

mailgun:
  api-key: api-key

line-notify:
  token: access-token

danal:
  cp-id: CPID
  cp-pwd: CPPWD
  cp-title: CPTITLE
  target-url: http://localhost:8080/members/%s/danal
