### Admin List
GET http://localhost:8080/admins
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Admin Detail
GET http://localhost:8080/admins/{{adminId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Admin Create
POST http://localhost:8080/admins
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "admin1@example.com",
  "username": "admin1",
  "password": "Test12#$",
  "fullName": "administrator"
}

### Admin Delete
DELETE http://localhost:8080/admins/{{adminId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Admin Change Username
PUT http://localhost:8080/admins/{{adminId}}/change-username
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "{{newUsername}}"
}

### Admin Change Full Name
PUT http://localhost:8080/admins/{{adminId}}/change-full-name
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "fullName": "{{newFullName}}"
}

### Admin Change Email
PUT http://localhost:8080/admins/{{adminId}}/change-email
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "{{newEmail}}"
}
