### Authenticate
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "grantType": "password",
  "username": "{{email}}",
  "password": "{{password}}",
  "captcha": "google-captcha-test"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### Refresh
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "grantType": "refresh_token",
  "refreshToken": "{{refreshToken}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### Password Change
PUT http://localhost:8080/auth/change-password
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": {{userId}},
  "oldPassword": "{{password}}",
  "newPassword": "{{password}}"
}

### Exists
GET http://localhost:8080/members/exists?email=admin@example.com
Content-Type: application/json
