### Member List
GET http://localhost:8080/members
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Member Detail
GET http://localhost:8080/members/7?
    roleCode=ROLE_SYSADMIN&
    status=NORMAL
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Member Create
POST http://localhost:8080/members
Content-Type: application/json

{
  "email": "{{email}}",
  "username": "{{username}}",
  "password": "{{password}}",
  "fullName": "{{fullName}}"
}

### Member Delete
DELETE http://localhost:8080/members/{{memberId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Member Reset Password
PUT http://localhost:8080/members/{{memberId}}/reset-password
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "newPassword": "Test12#$"
}

### Member Approve
PUT http://localhost:8080/members/{{memberId}}/approve
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Member Inactivate
PUT http://localhost:8080/members/{{memberId}}/inactivate
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Member Activate
PUT http://localhost:8080/members/{{memberId}}/activate
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Member Unregister
PUT http://localhost:8080/members/{{memberId}}/unregister
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Member Change Username
PUT http://localhost:8080/members/{{memberId}}/change-username
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "{{newUsername}}"
}

### Member Change Full Name
PUT http://localhost:8080/members/{{memberId}}/change-full-name
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "fullName": "{{newFullName}}"
}

### Member Change Email
PUT http://localhost:8080/members/{{memberId}}/change-email
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "{{newEmail}}"
}

### File upload
POST http://localhost:8080/members/upload
Content-Type: multipart/form-data; boundary=xxx

--xxx
Content-Disposition: form-data; name="file"; filename="test.png"

< /Users/jonghwa/Desktop/test.png
--xxx--
