### Staff List
GET http://localhost:8080/staffs
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Staff Detail
GET http://localhost:8080/staffs/{{staffId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Staff Create
POST http://localhost:8080/staffs
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": {{email}},
  "username": {{username}},
  "password": {{password}},
  "name": "staff"
}

### Staff Delete
DELETE http://localhost:8080/staffs/{{staffId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
