### Category List
GET http://localhost:8080/categories
Content-Type: application/json

### Category Detail
GET http://localhost:8080/categories/{{categoryId}}
Content-Type: application/json

### Category Root Create
POST http://localhost:8080/categories
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "테스트",
  "slug": "테스트",
  "description": "This is a a root category",
  "subDescription": "yet another category",
  "discountRate": 3.345,
  "position": 5
}

### Category Child Create
POST http://localhost:8080/categories/{{categoryId}}/add
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "third4",
  "slug": "third4",
  "description": "This is a category example.",
  "subDescription": "yet another category",
  "discountRate": 3.345
}

### Category Change Parent
PUT http://localhost:8080/categories/{{categoryId}}/parents/{{parentCategoryId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Category Update
PUT http://localhost:8080/categories/{{categoryId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "happy",
  "slug": "google",
  "description": "happy",
  "subDescription": "non refundable",
  "discountRate": 5.5
}

### Category Hide
PUT http://localhost:8080/categories/{{categoryId}}/hide
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Category Show
PUT http://localhost:8080/categories/{{categoryId}}/show
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Category Delete
DELETE http://localhost:8080/categories/{{categoryId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
