### Order List
GET http://localhost:8080/orders?userId={{userId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Order Detail
GET http://localhost:8080/orders/{{orderId}}?userId={{userId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Order Create
POST http://localhost:8080/orders
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": "29",
  "items": [
    {
      "productId": 5,
      "quantity": 2
    },
    {
      "productId": 7,
      "quantity": 3
    },
    {
      "productId": 6,
      "quantity": 4
    }
  ]
}

### Order Delete
DELETE http://localhost:8080/orders/{{orderId}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
