### User List
GET http://localhost:8080/users?roleCode=ROLE_SYSADMIN&status=NORMAL
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### User Detail
GET http://localhost:8080/users/1?roleCode=ROLE_SYSADMIN&status=NORMAL
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### User Delete

### User Approve

### User Inactivate

### User Activate

### User Unregister
