### Category Child Create
POST http://localhost:8080/categories/21/add
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "third3",
  "slug": "third3",
  "description": "This is a category example.",
  "subDescription": "yet another category",
  "discountRate": 3.345
}