### Category Hide
PUT http://localhost:8080/categories/11/update
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "nexon    ",
  "slug": "nexon",
  "description": "This is a category example.",
  "subDescription": "yet another category",
  "discountRate": 7.5
}