### Category Update
PUT http://localhost:8080/categories/11
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "happy",
  "slug": "google",
  "description": "happy",
  "subDescription": "non refundable",
  "discountRate": 5.5
}